# ── Hyarax Starterpack: Starship Prompt Config ──────────────────────────────
# Managed by Hyarax

format = """\
[](bg:#1e1e2e)\
$os\
$username\
[](bg:#1e1e2e fg:#1e1e2e)\
$directory\
[](fg:#1e1e2e bg:#94e2d5)\
$git_branch\
$git_status\
[](fg:#94e2d5 bg:#1e1e2e)\
$fill\
$cmd_duration\
$line_break\
$character\
"""

[character]
success_symbol = "[󰘧](bold green)"
error_symbol = "[󰘧](bold red)"

[directory]
style = "bg:#1e1e2e"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[$branch](bold black)"
style = "bg:#94e2d5"

[git_status]
format = '[[\[$all_status$ahead_behind\]]($style) '
style = "bg:#94e2d5"
conflicted = "🏳"
up_to_date = " "
untracked = "?"
stashed = "📦"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[cmd_duration]
min_time = 500
format = "⏱️[$duration]($style)"

[os]
disabled = false
style = "bg:#1e1e2e"
format = "[ $symbol]($style)"
symbols = { unix = "" }

[fill]
symbol = " "

[username]
show_always = true
style_user = "bg:#1e1e2e"
format = "[ $user ]($style)"
disabled = false
